### ISSUE TITLE
大佬现在没群，如何交流呀，请教

### ISSUE THREAD

**Issue by snowman32** [DHDAXCW/FusionWRT_x86_x64#17]
大佬现在没群，如何交流呀，请教

**Comment by DHDAXCW** [comment]
有群啊，直接加这里就好了  https://t.me/DHDAXCW

**Comment by snowman32** [comment]
我被你拉黑了吗....群进不去然后你的私聊我现在也不行

**Comment by snowman32** [comment]
![image](https://user-images.githubusercontent.com/75103950/176642426-cddd74a7-7f57-462c-8a90-dbffaab44385.png)
大佬麻烦解禁我..

**Comment by snowman32** [comment]
解决了。。。
