### ISSUE TITLE
關於 多線多撥 MWAN

### ISSUE THREAD

**Issue by sw629241** [DHDAXCW/FusionWRT_x86_x64#76]
您好~  

首先一直以來都使用您的版本，非常穩定好用，感謝您的付出。

最近更新時發現大大取消了四個版本，改為統一版本，為了能持續更新，所以最近也換上了 0423，但發現安裝了多線多撥原本還有一個MWAN的選單不見了，找了iStore相關也找不到...  

這個功能對我來說比較重要，因為要設置多線多撥後，取得多個IP，分配給區網內不同電腦使用，先前就是靠 多線多撥 + MWAMN 來實現指定不同IP給區網內不同電腦使用。

請問如何把 MWAN 功能裝上，或是有其他辦法能實現 指定IP給不同電腦使用嗎?  望不吝賜教，感謝。

**Comment by DHDAXCW** [comment]
虽然有用那就下版本集成吧。

**Comment by sw629241** [comment]
但這樣就等於放棄日後的更新了...   還是只能這樣，不管怎樣，還是謝謝您提供這樣好用的集成版本。

**Comment by DHDAXCW** [comment]
已内置进去了，5.6版的

**Comment by sw629241** [comment]
日安~ 

謝謝大大~
